#cloud-config


groups:

  - admingroup: [root,sys]

  - cloud-users

users:

  - default

  - name: luna

    gecos: Elly

    primary_group: Luna

    groups: admingroup

    lock_passwd: false

    passwd: $6$j212wezy$7H/1LT4f9/N3wpgNunhsIqtMj62OKiS3nyNwuizouQc3u7MbYCarYeAHWYPYb2FT.lbioDm2RrkJPb9BZMN1O/
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCT+k6OAN5nivYWxg+SInX30UcXRSFCYwKAjWXRJIUdFIuHxubj4nM1yiqxIxbAXxKebaOqJcu5YsMLfPjN8q2qOkFviSieAobwx/x0mqiPWktDDb1SJxeaC86fMzyofPhsBOK8Y5uGSc1SFGVDtPWUz8cF4gSL/oa1jPczwyChUB9zIh9jw2Aa0OCxJudBMX+h2Xj5XIgjR7ZoEEqYlsB4HolhzeC7D3ngqCBw636ugTUcx35webFTXkInKObroEr0cKVYyL2Tdd9YubsgE4f0AQjNmxhFm8AE2SZcRjdPnb5n4V7nZa64pRrQgF07046MsnXHBnBOpedaa09MNtfD

ssh_autorized_key : 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCT+k6OAN5nivYWxg+SInX30UcXRSFCYwKAjWXRJIUdFIuHxubj4nM1yiqxIxbAXxKebaOqJcu5YsMLfPjN8q2qOkFviSieAobwx/x0mqiPWktDDb1SJxeaC86fMzyofPhsBOK8Y5uGSc1SFGVDtPWUz8cF4gSL/oa1jPczwyChUB9zIh9jw2Aa0OCxJudBMX+h2Xj5XIgjR7ZoEEqYlsB4HolhzeC7D3ngqCBw636ugTUcx35webFTXkInKObroEr0cKVYyL2Tdd9YubsgE4f0AQjNmxhFm8AE2SZcRjdPnb5n4V7nZa64pRrQgF07046MsnXHBnBOpedaa09MNtfD
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQChqVgV7sOg/a6CfRT0b4D5Wk5jfPV492ZvD7PwWcvSy8RoOvXBnU16XNWV1YfgpSTRGoXNbtKjpxHtZKYpiJ1zrk9vAjmwniPO+3qfclb//CHx1FZCc0HMmp5gaqhbieJ7F5WIHveT7It9COjBj/aXvoj7ualdGfiaeb88CuQXSL7eeYFpNWhItu3HNPN/ImFxmi0JywfU0AZFOdetYQPnYwLaPaQ1SXX0lq+vy9W0ebXh6H0UsWE096Sn2YHvNStHH1qK81SuQqQ5kz638iD+iJK0UyjKRPyw8U1v5DrdDIcKodBKyHbkK4ghdlEe9nlrywiKaFFhrkFpotTqeEmg7siInR+4bcJ09V/78OZCEucM6Xi2sJoWwN1Ej49rNRq7iLe850Ui8/HNTwb91dzCGWFaYIHbMlbLpT8ltujFtiTSkE/smCvJj/sGWQ5GupyCwuxMhyQtKJiybgudYNJHuJT+RLi6qGMjfN3GYWod2UZOLYG9cTgLx8cA3+aK/Qc
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCFFkeF7e8cAmlh6idQ6Y8B6Or8lu0yNYWNdhHjDelrzCNP3tzz8P2y0GQXtbvUy1tmg43l+316iBXsIh3jh3wNcoPtKGhYI7wLU5UvxG0SAFrCLvCr/Rum84uDR4j7FpY+DKI5gs2CSnPA5QnLkgH34bqzRvdPlC+0bn8h9ux8UjOv6f2JYwvTL/R5gV0J/ngI3NYucfUJOzSQkGCCaEohmVXlHIZYJF/ZqA+j8+2DEk3YT32P/Pu5EcPRd0SIYFAWKXEOzncA9fW8w6JMvjhYUXAdcSmCqdIjoQqt7iPavuQh0JeFjGQ0AjjMOvOWntmif0eVubde7uyRKMIcdjQZ rsa-key-20220912
package_update: True

packages:
  - wget
  - git




write_files:
  - path: /etc/systemd/system/gitea.service
    content: |
        [Unit]
        Description=Gitea (Git with a cup of tea)
        After=syslog.target
        After=network.target
        ###
        # Don't forget to add the database service dependencies
        ###
        #
        #Wants=mysql.service
        #After=mysql.service
        #
        #Wants=mariadb.service
        #After=mariadb.service
        #
        #Wants=postgresql.service
        #After=postgresql.service
        #
        #Wants=memcached.service
        #After=memcached.service
        #
        #Wants=redis.service
        #After=redis.service
        #
        ###
        # If using socket activation for main http/s
        ###
        #
        #After=gitea.main.socket
        #Requires=gitea.main.socket
        #
        ###
        # (You can also provide gitea an http fallback and/or ssh socket too)
        #
        # An example of /etc/systemd/system/gitea.main.socket
        ###
        ##
        ## [Unit]
        ## Description=Gitea Web Socket
        ## PartOf=gitea.service
        ##
        ## [Socket]
        ## Service=gitea.service
        ## ListenStream=<some_port>
        ## NoDelay=true
        ##
        ## [Install]
        ## WantedBy=sockets.target
        ##
        ###

        [Service]
        # Modify these two values and uncomment them if you have
        # repos with lots of files and get an HTTP error 500 because
        # of that
        ###
        #LimitMEMLOCK=infinity
        #LimitNOFILE=65535
        RestartSec=2s
        Type=simple
        User=git
        Group=git
        WorkingDirectory=/var/lib/gitea/
        # If using Unix socket: tells systemd to create the /run/gitea folder, which will contain the gitea.sock file
        # (manually creating /run/gitea doesn't work, because it would not persist across reboots)
        #RuntimeDirectory=gitea
        ExecStart=/usr/local/bin/gitea web --config /etc/gitea/app.ini
        Restart=always
        Environment=USER=git HOME=/home/git GITEA_WORK_DIR=/var/lib/gitea
        # If you install Git to directory prefix other than default PATH (which happens
        # for example if you install other versions of Git side-to-side with
        # distribution version), uncomment below line and add that prefix to PATH
        # Don't forget to place git-lfs binary on the PATH below if you want to enable
        # Git LFS support
        #Environment=PATH=/path/to/git/bin:/bin:/sbin:/usr/bin:/usr/sbin
        # If you want to bind Gitea to a port below 1024, uncomment
        # the two values below, or use socket activation to pass Gitea its ports as above
        ###
        #CapabilityBoundingSet=CAP_NET_BIND_SERVICE
        #AmbientCapabilities=CAP_NET_BIND_SERVICE
        ###
        # In some cases, when using CapabilityBoundingSet and AmbientCapabilities option, you may want to
        # set the following value to false to allow capabilities to be applied on gitea process. The following
        # value if set to true sandboxes gitea service and prevent any processes from running with privileges
        # in the host user namespace.
        ###
        #PrivateUsers=false
        ###

        [Install]
        WantedBy=multi-user.target
 
runcmd:
  - [sudo, git, config, --global, user.name, "simplon-lanloBaptiste"]
  - [sudo, git, config, --global, user.email "simplonlanlobaptiste@gmail.com"]
  - [sudo, wget, "https://dl.gitea.io/gitea/1.16.7/gitea-1.16.7-linux-amd64", -O, /usr/local/bin/gitea ]
  - [sudo, chmod, +x, /usr/local/bin/gitea]
  - [sudo, adduser, --system, --shell, /bin/bash, --gecos, 'Git Version Control',--group, --disabled-password, --home, /home/git, git]
  - [sudo, mkdir, -p, /var/lib/gitea/custom]
  - [sudo, mkdir, -p, /var/lib/gitea/data]
  - [sudo, mkdir, -p, /var/lib/gitea/log]
  - [sudo, chown, -R, -v, "git:git", /var/lib/gitea]
  - [sudo, chmod, -R, "750", /var/lib/gitea]
  - [sudo, mkdir, -v, /etc/gitea]
  # - [sudo, git, clone, "https://github.com/simplon-lanloBaptiste/app.ini.git", /etc/gitea]
  - [sudo, chown, -R, "root:git", /etc/gitea]
  - [sudo, chmod, -R, "770", /etc/gitea]
  - [sudo, systemctl, enable, gitea]
  - [sudo, systemctl, start, gitea]
  - [sudo, apt, install, certbot, python3-certbot-apache]
  - [certbot, --apache]
  - [sudo, add-apt-repository ,"ppa:certbot/certbot"]
  - [sudo, certbot, certonly, --domain, b3g2eastus.eastus.cloudapp.azure.com, --email, baptistelanlo2@gmail.com, --agree-tos, --standalone]
  
